import z from "zod/v4";

export const verifone_3ds_lookup_response_schema = z.object({
    acs_transaction_id: z.string().optional(),
    acs_url: z.string().optional(),
    authentication_id: z.string(),
    cavv: z.string().optional(),
    challenge_required: z.string().optional(),
    card_brand: z.string().optional(),
    ds_transaction_id: z.string().optional(),
    eci_flag: z.string().optional(),
    enrolled: z.string().optional(),
    error_desc: z.string().optional(),
    error_no: z.string(),
    order_id: z.string().optional(),
    pares_status: z.string().optional(),
    payload: z.string().optional(),
    signature_verification: z.string().optional(),
    threeds_version: z.string().optional(),
    transaction_id: z.string(),
});

export const verifone_payment_response_schema = z.object({
    id: z.string(),
    payment_provider_contract: z.string(),
    amount: z.number(),
    blocked: z.boolean(),
    merchant_reference: z.string().optional(),
    payment_product: z.string(),
    // https://verifone.cloud/api-catalog/verifone-ecommerce-api#tag/Ecom-Payments/operation/saleTransaction
    status: z.enum([
        "INITIATED",
        "AUTHORIZED",
        "AUTHORIZATION_VOIDED",
        "CANCELLED",
        "CUSTOMER_ACCEPTED",
        "REFUNDED",
        "FAILED",
        "PENDING",
        "DECLINED",
        "SETTLEMENT_CANCELLED",
        "SETTLEMENT_REQUESTED",
        "SETTLEMENT_SUBMITTED",
        "SETTLEMENT_COMPLETED",
        "SETTLEMENT_PARTIAL",
        "SETTLEMENT_DECLINED",
        "VOIDED",
        "UNKNOWN",
    ]),
    customer_details: z
        .object({
            first_name: z.string().optional(),
            last_name: z.string().optional(),
            email_address: z.string().optional(),
            billing: z.object({
                address_1: z.string().optional(),
                city: z.string().optional(),
                country: z.string().optional(),
            }),
        })
        .optional(),
    authorization_code: z.string(),
    scheme_reference: z.string(),
    created_by: z.string(),
    cvv_present: z.boolean(),
    cvv_result: z.enum(["1", "0"]),
    stored_credential: z.object(),
    details: z.object({ auto_capture: z.boolean() }),
    reason_code: z.string(),
    rrn: z.string(),
    shopper_interaction: z.string(),
    stan: z.string(),
    threed_authentication: z.object({
        eci_flag: z.string(),
        enrolled: z.string(),
        cavv: z.string(),
        pares_status: z.string(),
        threeds_version: z.string(),
        ds_transaction_id: z.string(),
    }),
    reversal_status: z.string(),
    additional_data: z.object({
        acquirer_response_code: z.string(),
        initiator_trace_id: z.string(),
    }),
    promo_financing_result: z.object(),
    card_details: z.object({
        masked_card_number: z.string(),
        expiry_year: z.number(),
        expiry_month: z.number(),
    }),
    balance_amount: z.number(),
    payment_account_reference: z.string(),
});
